version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  EnableNuGetPackageRestore: true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    cd src

    nuget restore
build:
  project: src\Gmtl.CodeWatch.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 4NFCV0P1k0CmzDxS3oEj4svkyaLF5SBctZop1acIBdHoVFNdwm482o3tLGdnXW6+

